//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Infatlan_STEI_Inventario.SapActivos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_AF_INFATLAN", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_AF_INFATLAN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZWS_AF_CONSULTAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_AF_INFATLAN() {
            this.Url = global::Infatlan_STEI_Inventario.Properties.Settings.Default.Infatlan_STEI_Inventario_SapActivos_ZWS_AF_INFATLAN;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZWS_AF_CONSULTACompletedEventHandler ZWS_AF_CONSULTACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_AF_INFATLAN:ZWS_AF_CONSULTARequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZWS_AF_CONSULTAResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZWS_AF_CONSULTAResponse ZWS_AF_CONSULTA([System.Xml.Serialization.XmlElementAttribute("ZWS_AF_CONSULTA", Namespace="urn:sap-com:document:sap:rfc:functions")] ZWS_AF_CONSULTA ZWS_AF_CONSULTA1) {
            object[] results = this.Invoke("ZWS_AF_CONSULTA", new object[] {
                        ZWS_AF_CONSULTA1});
            return ((ZWS_AF_CONSULTAResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZWS_AF_CONSULTAAsync(ZWS_AF_CONSULTA ZWS_AF_CONSULTA1) {
            this.ZWS_AF_CONSULTAAsync(ZWS_AF_CONSULTA1, null);
        }
        
        /// <remarks/>
        public void ZWS_AF_CONSULTAAsync(ZWS_AF_CONSULTA ZWS_AF_CONSULTA1, object userState) {
            if ((this.ZWS_AF_CONSULTAOperationCompleted == null)) {
                this.ZWS_AF_CONSULTAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZWS_AF_CONSULTAOperationCompleted);
            }
            this.InvokeAsync("ZWS_AF_CONSULTA", new object[] {
                        ZWS_AF_CONSULTA1}, this.ZWS_AF_CONSULTAOperationCompleted, userState);
        }
        
        private void OnZWS_AF_CONSULTAOperationCompleted(object arg) {
            if ((this.ZWS_AF_CONSULTACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZWS_AF_CONSULTACompleted(this, new ZWS_AF_CONSULTACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_AF_CONSULTA {
        
        private string fECHA_FINALField;
        
        private string fECHA_INICIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHA_FINAL {
            get {
                return this.fECHA_FINALField;
            }
            set {
                this.fECHA_FINALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHA_INICIO {
            get {
                return this.fECHA_INICIOField;
            }
            set {
                this.fECHA_INICIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_AF_INFT {
        
        private string sOCIEDADField;
        
        private string aCTIVOFIJOField;
        
        private string sECUENCIAField;
        
        private string iDTIPOARTICULOField;
        
        private string tIPOARTICULOField;
        
        private string iDACREEDORField;
        
        private string aCREEDORField;
        
        private string rESPONSABLEField;
        
        private string dIRECCIONField;
        
        private string tELEFONOField;
        
        private string dESCRIPCIONField;
        
        private decimal pRECIOField;
        
        private string eJERCICIOField;
        
        private string fECHAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOCIEDAD {
            get {
                return this.sOCIEDADField;
            }
            set {
                this.sOCIEDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACTIVOFIJO {
            get {
                return this.aCTIVOFIJOField;
            }
            set {
                this.aCTIVOFIJOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SECUENCIA {
            get {
                return this.sECUENCIAField;
            }
            set {
                this.sECUENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDTIPOARTICULO {
            get {
                return this.iDTIPOARTICULOField;
            }
            set {
                this.iDTIPOARTICULOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPOARTICULO {
            get {
                return this.tIPOARTICULOField;
            }
            set {
                this.tIPOARTICULOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDACREEDOR {
            get {
                return this.iDACREEDORField;
            }
            set {
                this.iDACREEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACREEDOR {
            get {
                return this.aCREEDORField;
            }
            set {
                this.aCREEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESPONSABLE {
            get {
                return this.rESPONSABLEField;
            }
            set {
                this.rESPONSABLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EJERCICIO {
            get {
                return this.eJERCICIOField;
            }
            set {
                this.eJERCICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
            }
        }

        internal ZWS_AF_CONSULTAResponse ZWS_AF_CONSULTA(ZWS_AF_CONSULTA vConsulta)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_FI_MSG {
        
        private string cOD_MSGField;
        
        private string dESCRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_MSG {
            get {
                return this.cOD_MSGField;
            }
            set {
                this.cOD_MSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRI {
            get {
                return this.dESCRIField;
            }
            set {
                this.dESCRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_AF_CONSULTAResponse {
        
        private ZST_FI_MSG[] zAF_DATA_MSGField;
        
        private ZWS_AF_INFT[] zAF_DATA_TABField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_FI_MSG[] ZAF_DATA_MSG {
            get {
                return this.zAF_DATA_MSGField;
            }
            set {
                this.zAF_DATA_MSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZWS_AF_INFT[] ZAF_DATA_TAB {
            get {
                return this.zAF_DATA_TABField;
            }
            set {
                this.zAF_DATA_TABField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ZWS_AF_CONSULTACompletedEventHandler(object sender, ZWS_AF_CONSULTACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZWS_AF_CONSULTACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZWS_AF_CONSULTACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZWS_AF_CONSULTAResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZWS_AF_CONSULTAResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591